<?php
/* @var $this SiteController */
/* @var $model LoginForm */
/* @var $form CActiveForm  */

$this->pageTitle = Yii::app()->name . ' - Search';
$this->breadcrumbs = array(
    'Search',
);
?>


<div class="sisi">
	<div class="kiri">
		<div class="sub">
			<?php $this->widget('application.extensions.videojs.EVideoJS', array(
					'options' => array(
						// Unique identifier, is autogenerated by default, useful for jQuery integrations.
						'id' => false,
						// Video and poster width in pixels
						'width' => '100%',
						// Video and poster height in pixels
						'height' => 365,
						// Poster image absolute URL
						'poster' => false,
						// Absolute URL of the video in MP4 format
						'video_mp4' => Yii::app()->request->baseUrl.'/uploads/4d3db01b48a58d7736fa8bb92c0288e60391c8ab.mp4',
						// Absolute URL of the video in OGV format
						'video_ogv' => false,
						// Absolute URL of the video in WebM format
						'video_webm' => false,
						// Use Flash fallback player ?
						'flash_fallback' => true,
						// Address of custom Flash player to use as fallback
						'flash_player' => 'http://releases.flowplayer.org/swf/flowplayer-3.2.1.swf',
						// Show controls ?
						'controls' => true,
						// Preload video content ?
						'preload' => true,
						// Autostart the playback ?
						'autoplay' => false,
						// Show VideoJS support link ?
						'support' => true,
						// Show video download links ?
						'download' => false,
					),
				));
				?>
		</div>
	</div>
	<div class="kanan">
		<div class="sub">
			<section class="att">
				<h2>Subscribe Now</h2>
			</section>
			<form method="post" action="" id="searchForm" class="search-form">
			<input type="text" id="" name="" placeholder="Email" class="span4">
			<button name="yt3" type="submit" class="btn">SUBMIT</button>
			</form>
		</div>
		<div class="soksial">
			<ul class="konek">
				<li><a href="" class="fb"><img src="<?php echo Yii::app()->request->baseUrl; ?>/images/fb.png" alt="Sign In Facebook"/></a></li>
				<li><a href="" class="twit"><img src="<?php echo Yii::app()->request->baseUrl; ?>/images/twit.png" alt="Sign In Twitter"/></a></li>
				<li><a href="" class="twit"><img src="<?php echo Yii::app()->request->baseUrl; ?>/images/log.png" alt="Sign In Account"/></a></li>
			</ul>
			<div class="tex">
				<h2>Lorem ipsum dolor sit amet</h2>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec semper urna id massa rutrum imperdiet. Duis ut adipiscing tellus. Duis blandit, nisl dapibus tincidunt adipiscing, nisl orci consectetur mi, eget consequat orci metus ut urna. Praesent laoreet suscipit commodo. 
				</p>
			</div>
		</div>
	</div>
</div>

<div class="main">
	<ul id="cbp-bislideshow" class="cbp-bislideshow">
		<li><img src="<?php echo Yii::app()->request->baseUrl; ?>/images/1.jpg" alt="image01"/></li>
		<li><img src="<?php echo Yii::app()->request->baseUrl; ?>/images/2.jpg" alt="image02"/></li>
		<li><img src="<?php echo Yii::app()->request->baseUrl; ?>/images/3.jpg" alt="image03"/></li>
		<li><img src="<?php echo Yii::app()->request->baseUrl; ?>/images/4.jpg" alt="image04"/></li>
		<li><img src="<?php echo Yii::app()->request->baseUrl; ?>/images/5.jpg" alt="image05"/></li>
		<li><img src="<?php echo Yii::app()->request->baseUrl; ?>/images/6.jpg" alt="image06"/></li>
	</ul>
</div>